server:
  port: 8088


spring:
  application:
    name: camunda-demo
    #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true